// <auto-generated />
using Example4.ShopCode.EfCoreCode;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Example4.ShopCode.EfCoreCode.Migrations
{
    [DbContext(typeof(RetailDbContext))]
    partial class RetailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("retail")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Example4.ShopCode.EfCoreClasses.RetailOutlet", b =>
                {
                    b.Property<int>("RetailOutletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthPTenantId")
                        .HasColumnType("int");

                    b.Property<string>("DataKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RetailOutletId");

                    b.HasIndex("DataKey");

                    b.HasIndex("FullName")
                        .IsUnique()
                        .HasFilter("[FullName] IS NOT NULL");

                    b.ToTable("RetailOutlets");
                });

            modelBuilder.Entity("Example4.ShopCode.EfCoreClasses.ShopSale", b =>
                {
                    b.Property<int>("ShopSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumSoldReturned")
                        .HasColumnType("int");

                    b.Property<string>("ReturnReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopStockId")
                        .HasColumnType("int");

                    b.HasKey("ShopSaleId");

                    b.HasIndex("DataKey");

                    b.HasIndex("ShopStockId");

                    b.ToTable("ShopSales");
                });

            modelBuilder.Entity("Example4.ShopCode.EfCoreClasses.ShopStock", b =>
                {
                    b.Property<int>("ShopStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumInStock")
                        .HasColumnType("int");

                    b.Property<decimal>("RetailPrice")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantItemId")
                        .HasColumnType("int");

                    b.HasKey("ShopStockId");

                    b.HasIndex("DataKey");

                    b.HasIndex("TenantItemId");

                    b.ToTable("ShopStocks");
                });

            modelBuilder.Entity("Example4.ShopCode.EfCoreClasses.ShopSale", b =>
                {
                    b.HasOne("Example4.ShopCode.EfCoreClasses.ShopStock", "StockItem")
                        .WithMany()
                        .HasForeignKey("ShopStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("Example4.ShopCode.EfCoreClasses.ShopStock", b =>
                {
                    b.HasOne("Example4.ShopCode.EfCoreClasses.RetailOutlet", "Shop")
                        .WithMany()
                        .HasForeignKey("TenantItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });
#pragma warning restore 612, 618
        }
    }
}
